### ISSUE TITLE
Unable to start successfully

### ISSUE THREAD

**Issue by maui-maui** [mustafaozhan/GoogleIntegratedSystemConky#4]
Error: https://ghostbin.com/paste/63xab

conkyrc: https://ghostbin.com/paste/j3o4w

output of `ls .config/GoogleIntegratedSystemConky`: https://ghostbin.com/paste/vapvv

![image](https://user-images.githubusercontent.com/24946168/35005428-f3c6f4f4-fab8-11e7-998a-3b7836597371.png)

ignore the right conky thats my own im customizing for fun

**Comment by mustafaozhan** [comment]
Hello,

It is a little bit weird firstly i have to ask you some questions.

What is your desktop enviroments ? It seems like Mate or XFCE. If it is XFCE are you saving sessions before you turn off the computer ? Because it seems that conky override itself.

Secondly can you kill all conkies with  `killall conky` then just run the conky from repository with command `sh ~/.config/GoogleIntegratedSystemConky/gisc.sh start` it seems that your own conky placed itself on Google Keep part of my conky.

Lastly, do you have second monitor ? or did you played with `~/.config/GoogleIntegratedSystemConky/conkyrc` because conky didn't start where it suppose to start. And also please let me know what is your screen resolution.

**Comment by maui-maui** [comment]
resolution: 1366x768
env: mate
only one display
and only minorly changed conkyrc (but errored before i made any changes

**Comment by maui-maui** [comment]
and i killed my conky and still
![image](https://user-images.githubusercontent.com/24946168/35014465-4c75bafa-fad6-11e7-89e1-6e4058020d51.png)

**Comment by maui-maui** [comment]
clock also messes up at hour change
![image](https://user-images.githubusercontent.com/24946168/35014577-b1749980-fad6-11e7-9273-973be7d15421.png)

**Comment by mustafaozhan** [comment]
The problem is it starting somewhere not in the screen 
in `~/.config/GoogleIntegratedSystemConky/conkyrc`
change 
```
minimum_size 1600 900
maximum_width 1600
```
with 
```
minimum_size 1366 768
maximum_width 1366
```

Lastly, change `own_window_type normal` to `own_window_type desktop`

You should know that this configuration for 1600*900 screen resolution. So it is normal that it is not resizing how you wish.

**Comment by maui-maui** [comment]
![image](https://user-images.githubusercontent.com/24946168/35015475-2a50b566-fada-11e7-8d9b-4e4e9d4247fa.png)

**Comment by maui-maui** [comment]
getting there xD

**Comment by mustafaozhan** [comment]
try with `own_window_type` actually the problem in here not about the GISC it is about desktop environment or window manager because we need to make some conky preferences different when switch the environments. They have different approaches for transparency. You can cheat from you own conky file we need to play with the values 
```
#Window Specification
own_window no
own_window_type normal
own_window_transparent yes
own_window_argb_visual yes
```

**Comment by mustafaozhan** [comment]
It is not an issue related to the project, it is about conky configuration according to desktop environment and screen resolution also there is no feedback.
