### ISSUE TITLE
Notes not comming!

### ISSUE THREAD

**Issue by naryal2580** [mustafaozhan/GoogleIntegratedSystemConky#7]
# Hello, bro ... I have some issues 
## issues
- I am not able to get a text from Google Keep I am getting two black blocks instead of my Notes. 
- And, also Network like IP, up and down is not coming...
## ScreenShot:
![Desktop Home Screenshot](https://naryal2580.github.io/pikk.png)

**Comment by mustafaozhan** [comment]
Hello,

For your second problem you need to open conkyrc and change the wlp2s0 with your computer wlan interface. Note that if you use cable base internet it will start with eth i guess. And also you probably do not have /data partition so that's why it shows data 0B / 0B.

For your first problem it seems that something working 😄 Do you follow the Instructions in README ?  If yes can you run gisc.sh from terminal and share output ?

**Comment by naryal2580** [comment]
## Well thanks for 2st one...
## Yes, I have followed the thing... But, It's not working sending you output...

**Comment by mustafaozhan** [comment]
It is so weird there is nothing related with Google Keep script. So it means it works fine you probably have a problem with configuration.

So make sure of this 2:

1- Locate Your Notes in Google Keep as a Title 'To-do'
2- make sure that you put your gmail and password in config.xml

**Comment by naryal2580** [comment]
## Yeah did it already... let me show you the pikz...
![Desktop Home Screenshot](https://naryal2580.github.io/ssss.png)
![Desktop Home Screenshot](https://naryal2580.github.io/dsf.png)

**Comment by naryal2580** [comment]
# Didn't work!!! BYE

**Comment by naryal2580** [comment]
# Bro!!

**Comment by mustafaozhan** [comment]
`python python-appdirs python-packaging python-pyparsing python-setuptool  python-six python-pip python-beautifulsoup4 python-requests python-lxml`

Do you have all of them installed ? they are the dependencies.

**Comment by naryal2580** [comment]
# Yes, all of them
```Requirement already satisfied: ...``` 

## Bro, I think something is wrong with the display
### ⮞ Sometimes it shows gradient fill in small blocks,
### ⮞ Sometimes it shows some glitchy blocks.
#### Now, It's gradient fill
![image](https://user-images.githubusercontent.com/34544253/39737515-31729db6-52a3-11e8-8684-30c50c9248e8.png)

**Comment by mustafaozhan** [comment]
Hello,

You can try with last version of repo i think it is done :smile: And let me know if it will work for you too.

**Comment by mustafaozhan** [comment]
`killall conky` than start again after you accept from your Google account (only for first time).  The problem was because of Google Keep changed structure.
Now if you have any problem related Script you will get `Connection to Google Keep failed !` on the desktop as a conky text. Otherwise it is related your Google configuration or config.xml file.

**Comment by mustafaozhan** [comment]
Do you update all files with the last commit ? i modified multiple files ? it should work now. in 2 of my computer it is working like a charm. Use completely last version delete old files and download from repo again.

**Comment by naryal2580** [comment]
## Awesome Now, it's working fine...
![image](https://user-images.githubusercontent.com/34544253/39908489-f42762aa-550b-11e8-802d-40bd12b27584.png)
# THANKS!!!

**Comment by mustafaozhan** [comment]
Perfect ! I am glad that we solved your issue :smile: Enjoy it bro
