### ISSUE TITLE
How to change screen resolution to 1920x1080?

### ISSUE THREAD

**Issue by hugohabicht01** [mustafaozhan/GoogleIntegratedSystemConky#8]
What should I change for a screenresolution 1920x1080?

**Comment by mustafaozhan** [comment]
basically you need to change this lines 
`minimum_size 1600 900
maximum_width 1600`
in conkyrc file.

Lines in the background will not fit the conky texts. So you need to change position of every item in conkyrc one by one. I do not have 1920x1080 monitor/screen so that's why i am unable to help to you about it.
