### ISSUE TITLE
Conky on a mac

### ISSUE THREAD

**Issue by datatalking** [mustafaozhan/GoogleIntegratedSystemConky#9]
Will this program work if installed on a mac or does it need its own full javascript runtime virtual environment?

**Comment by mustafaozhan** [comment]
Hello,
this is kind of configuration for conky program in Linux. Because of I do not have a Mac computer i am not able to try it but I found a [repository](https://github.com/Conky-for-macOS/conky-for-macOS). You can try it and let us know 😄  And It does now have any connection with JavaScript runtime virtual environment.
